---
argument_specs:
  main:
    short_description: Run certification tooling against containerized applications.
    description:
      - This is a purpose-made role for executing container certification
      - tooling ("OpenShift Preflight")) against one or more container images.
    options:
      certify_containers_target_image:
        description: The container image reference to target
        required: true
        type: str
      certify_containers_working_dir:
        description:
          - This is the base working directory for the role.
          - The role will create working directories, or assume
          - the location of specific files based on this path.
          - By default, this value is empty, which makes derived
          - values calculated to be relative to the current working
          - directory when called.
        required: false
        type: str
      certify_containers_userfiles_dir:
        description:
          - This directory is where user-provided files the role must
          - use should exist. By default, this is calculated relative
          - to the certify_containers_working_dir.
        required: false
        type: str
      certify_containers_cert_logs_dir:
        description:
          - This directory is where the role will write log files for
          - each individual tool run. By default, this is calculated
          - relative to the certify_containers_working_dir.
        required: false
        type: str
      certify_containers_preflight_cmd:
        description:
          - This is the location of the Preflight command to run. This file
          - is expected to be executable, and will not be made so by the
          - role.
        required: false
        type: str
      certify_containers_pyxis_env:
        description: The environment to target.
        required: false
        type: str
        choices:
          - '' # Accept empty but defined values from the user.
          - stage
          - prod
      certify_containers_submit_results:
        description:
          - Whether results should be submitted. Submitting results
          - requires additional inputs, and so setting this to
          - true also enforces that the other required inputs
          - are set and valid.
        required: false
        type: bool
      certify_containers_docker_config_filename:
        description:
          - The filename for the docker_config to use for image pulls.
          - This file is expected to be a path relative to the
          - value set for certify_containers_userfiles_dir.
        required: false
        type: str
      certify_containers_component_id:
        description:
          - The _id value for a given Certification component.
          - This is a required input if the argument
          - certify_containers_submit_results is set to true.
        required: false
        type: str
      certify_containers_image_platform:
        description:
          - A specific platform to target on the
          - certify_containers_target_image. This is mostly
          - useful if you want to test a single platform of a
          - multiarch image, or if you want to test a non-native
          - platform for the runtime system.
        required: false
        type: str
      certify_containers_preflight_loglevel:
        description:
          - The preflight log verbosity setting.
        required: false
        type: str
        choices:
          - '' # Accept empty but defined values from the user.
          - err
          - warn
          - info
          - debug
          - trace
      certify_containers_pyxis_api_token:
        description:
          - The API token used for submission.
        required: false
        type: str
...
