name: Build Main

on:
  push:
    branches: [ main, ghactions ]
  
jobs:
  build-certify-containers:
    env:
      IMAGE_NAME: certify-containers
    name: Build and and push main snapshots for certify-containers
    strategy: 
      matrix:
        architecture:
        - amd64
        - arm64
        # - ppc64le,
        # - s390x
        platform: [linux]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
  
    - name: set short sha
      run: echo SHA_SHORT=$(git rev-parse --short HEAD) >> $GITHUB_ENV

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
        
    - name: Build Image
      id: build-image
      uses: redhat-actions/buildah-build@v2
      with:
        image: ${{ secrets.IMAGE_REGISTRY }}/${{ env.IMAGE_NAME }}
        tags: ${{ env.SHA_SHORT }}-${{ matrix.platform }}-${{ matrix.architecture }}
        archs: ${{ matrix.architecture }}
        context: ./images/certify-containers
        build-args: |
          arch=${{ matrix.architecture }}
          commit=${{ github.sha }}
        dockerfiles: |
          ./images/certify-containers/Containerfile

    - name: Push Image
      id: push-image
      uses: redhat-actions/push-to-registry@v2
      with:
        image: ${{ env.IMAGE_NAME }}
        tags: ${{ env.SHA_SHORT }}-${{ matrix.platform }}-${{ matrix.architecture }}
        registry: ${{ secrets.IMAGE_REGISTRY }}
        username: ${{ secrets.REGISTRY_USER }}
        password: ${{ secrets.REGISTRY_TOKEN }}

    - name: Print image url
      run: echo "Image pushed to ${{ steps.push-image.outputs.registry-paths }}"
    
    outputs:
      image-name: ${{ env.IMAGE_NAME }}
      image-version: ${{ env.SHA_SHORT }}

  build-multiarch-certify-containers:
    needs: build-certify-containers
    uses: ./.github/workflows/build-multiarch.yaml
    with:
      name: ${{ needs.build-certify-containers.outputs.image-name }}
      tag: ${{ needs.build-certify-containers.outputs.image-version }}
      sign: false # do not sign images built on main
    secrets:
      registry: ${{ secrets.IMAGE_REGISTRY }}
      user: ${{ secrets.REGISTRY_USER }}
      password: ${{ secrets.REGISTRY_TOKEN }}

  tag-latest-certify-containers:
    needs: 
    - build-multiarch-certify-containers
    - build-certify-containers
    uses: ./.github/workflows/tag-image.yaml
    with:
      image-name: ${{ needs.build-certify-containers.outputs.image-name }}
      target-tag: ${{ needs.build-certify-containers.outputs.image-version }}
      with-tag: latest
    secrets:
      registry: ${{ secrets.IMAGE_REGISTRY }}
      registry-username: ${{ secrets.REGISTRY_USER }}
      registry-credential: ${{ secrets.REGISTRY_TOKEN }}

  build-certify-helmcharts:
    env:
      IMAGE_NAME: certify-helmcharts
    name: Build and and push main snapshots for certify-helmcharts
    strategy: 
      matrix:
        architecture:
        - amd64
        - arm64
        # - ppc64le,
        # - s390x
        platform: [linux]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: set short sha
      run: echo SHA_SHORT=$(git rev-parse --short HEAD) >> $GITHUB_ENV

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
        
    - name: Build Image
      id: build-image
      uses: redhat-actions/buildah-build@v2
      with:
        image: ${{ secrets.IMAGE_REGISTRY }}/${{ env.IMAGE_NAME }}
        tags: ${{ env.SHA_SHORT }}-${{ matrix.platform }}-${{ matrix.architecture }}
        archs: ${{ matrix.architecture }}
        context: ./images/certify-helmcharts
        build-args: |
          arch=${{ matrix.architecture }}
          commit=${{ github.sha }}
        dockerfiles: |
          ./images/certify-helmcharts/Containerfile

    - name: Push Image
      id: push-image
      uses: redhat-actions/push-to-registry@v2
      with:
        image: ${{ env.IMAGE_NAME }}
        tags: ${{ env.SHA_SHORT }}-${{ matrix.platform }}-${{ matrix.architecture }}
        registry: ${{ secrets.IMAGE_REGISTRY }}
        username: ${{ secrets.REGISTRY_USER }}
        password: ${{ secrets.REGISTRY_TOKEN }}

    - name: Print image url
      run: echo "Image pushed to ${{ steps.push-image.outputs.registry-paths }}"
    
    outputs:
      image-name: ${{ env.IMAGE_NAME }}
      image-version: ${{ env.SHA_SHORT }}

  build-multiarch-certify-helmcharts:
    needs: build-certify-helmcharts
    uses: ./.github/workflows/build-multiarch.yaml
    with:
      name: ${{ needs.build-certify-helmcharts.outputs.image-name }}
      tag: ${{ needs.build-certify-helmcharts.outputs.image-version }}
      sign: false # do not sign images built on main
    secrets:
      registry: ${{ secrets.IMAGE_REGISTRY }}
      user: ${{ secrets.REGISTRY_USER }}
      password: ${{ secrets.REGISTRY_TOKEN }}

  tag-latest-certify-helmcharts:
    needs: 
    - build-multiarch-certify-helmcharts
    - build-certify-helmcharts
    uses: ./.github/workflows/tag-image.yaml
    with:
      image-name: ${{ needs.build-certify-helmcharts.outputs.image-name }}
      target-tag: ${{ needs.build-certify-helmcharts.outputs.image-version }}
      with-tag: latest
    secrets:
      registry: ${{ secrets.IMAGE_REGISTRY }}
      registry-username: ${{ secrets.REGISTRY_USER }}
      registry-credential: ${{ secrets.REGISTRY_TOKEN }}

  build-certify-operators:
    env:
      IMAGE_NAME: certify-operators
    name: Build and and push main snapshots for certify-operators
    strategy: 
      matrix:
        architecture:
        - amd64
        - arm64
        # - ppc64le,
        # - s390x
        platform: [linux]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: set short sha
      run: echo SHA_SHORT=$(git rev-parse --short HEAD) >> $GITHUB_ENV

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
        
    - name: Build Image
      id: build-image
      uses: redhat-actions/buildah-build@v2
      with:
        image: ${{ secrets.IMAGE_REGISTRY }}/${{ env.IMAGE_NAME }}
        tags: ${{ env.SHA_SHORT }}-${{ matrix.platform }}-${{ matrix.architecture }}
        archs: ${{ matrix.architecture }}
        context: ./images/certify-operators
        build-args: |
          arch=${{ matrix.architecture }}
          commit=${{ github.sha }}
        dockerfiles: |
          ./images/certify-operators/Containerfile

    - name: Push Image
      id: push-image
      uses: redhat-actions/push-to-registry@v2
      with:
        image: ${{ env.IMAGE_NAME }}
        tags: ${{ env.SHA_SHORT }}-${{ matrix.platform }}-${{ matrix.architecture }}
        registry: ${{ secrets.IMAGE_REGISTRY }}
        username: ${{ secrets.REGISTRY_USER }}
        password: ${{ secrets.REGISTRY_TOKEN }}

    - name: Print image url
      run: echo "Image pushed to ${{ steps.push-image.outputs.registry-paths }}"
    
    outputs:
      image-name: ${{ env.IMAGE_NAME }}
      image-version: ${{ env.SHA_SHORT }}

  build-multiarch-certify-operators:
    needs: build-certify-operators
    uses: ./.github/workflows/build-multiarch.yaml
    with:
      name: ${{ needs.build-certify-operators.outputs.image-name }}
      tag: ${{ needs.build-certify-operators.outputs.image-version }}
      sign: false # do not sign images built on main
    secrets:
      registry: ${{ secrets.IMAGE_REGISTRY }}
      user: ${{ secrets.REGISTRY_USER }}
      password: ${{ secrets.REGISTRY_TOKEN }}

  tag-latest-certify-operatorsd:
    needs: 
    - build-multiarch-certify-operators
    - build-certify-operators
    uses: ./.github/workflows/tag-image.yaml
    with:
      image-name: ${{ needs.build-certify-operators.outputs.image-name }}
      target-tag: ${{ needs.build-certify-operators.outputs.image-version }}
      with-tag: latest
    secrets:
      registry: ${{ secrets.IMAGE_REGISTRY }}
      registry-username: ${{ secrets.REGISTRY_USER }}
      registry-credential: ${{ secrets.REGISTRY_TOKEN }}