# Workflow "Release" responds to published releases and tags creates or moves tags
# associated with the release ref.
name: Release

on:
  release:
    types:
      - published

jobs:
  populate-release-data:
    outputs:
      release-tag: ${{ steps.populate-release-data.outputs.release-tag }}
      sha-short: ${{ steps.populate-release-data.outputs.sha-short }}
    runs-on: ubuntu-latest
    steps:
    - name: Populate release data
      id: populate-release-data
      run: |
        echo release-tag=$(echo ${{ github.ref }} | cut -d '/' -f 3) | tee -a $GITHUB_OUTPUT
        echo sha-short=$(expr substr "${{ github.sha }}" 1 7) | tee -a $GITHUB_OUTPUT
  push-release-tag:
    needs: [populate-release-data]
    strategy: 
      matrix:
        image:
          - certify-containers
          - certify-operators
          - certify-helmcharts
    uses: ./.github/workflows/tag-image.yaml
    with:
      image-name: ${{ matrix.image }}
      target-tag: ${{ needs.populate-release-data.outputs.sha-short }}
      with-tag: ${{ needs.populate-release-data.outputs.release-tag }}
    secrets:
      registry: ${{ secrets.IMAGE_REGISTRY }}
      registry-username: ${{ secrets.REGISTRY_USER }}
      registry-credential: ${{ secrets.REGISTRY_TOKEN }}