# Workflow "Tag Image" tags the input image with a new tag, and pushes that tag
# to the specified registry. The driving use case is moving floating tags, such
# as the "latest" tag.
name: Tag Image

on:
  workflow_call:
    inputs:
      image-name:
        required: true
        type: string
        description: The name of the image. E.g. "my-image".
      target-tag:
        required: true
        type: string
        description: What pre-existing tag will receive the new tag.
      with-tag:
        required: true
        type: string
        description: The new tag to add to the previous tag.
    secrets:
      registry:
        required: true
        description: The registry endpoint where the image resides, including the namespace.
      registry-username:
        required: true
        description: The username used to authenticate to the registry
      registry-credential:
        required: true
        description: the authentication credential used to authenticate to the registry
  
jobs:
  tag-image:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.23
    - name: Install Skopeo
      run: |
        sudo apt-get update && sudo apt install libgpgme-dev libassuan-dev libbtrfs-dev pkg-config -y
        go install github.com/containers/skopeo/cmd/skopeo@v1.18.0
        skopeo -v
    - name: Authenticate to registry
      uses: redhat-actions/podman-login@v1
      with:
        registry: ${{ secrets.registry }}
        username: ${{ secrets.registry-username }}
        password: ${{ secrets.registry-credential }}
    - name: Tag image
      run: |
        skopeo copy \
          --preserve-digests \
          --multi-arch index-only \
          docker://${{ secrets.registry }}/${{ inputs.image-name }}:${{ inputs.target-tag }} \
          docker://${{ secrets.registry }}/${{ inputs.image-name }}:${{ inputs.with-tag }}